apiVersion:  apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-app
    template:
      metadata:
        labels:
          app: ci-cd-app
      spec:
        containers:
        - name: ci-cd-app
          image: us-central1-docker.pkg.dev/ci-cd-implementation-471504/ci-cd-app/ci-cd-app:latest
          ports:
          - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app
spec:
  selector:
    app: ci-cd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


